name: mingchen-selfhost

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    restart: unless-stopped

  calibre:
    image: lscr.io/linuxserver/calibre:latest
    security_opt:
      - seccomp=unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    ports:
      - 8080
      - 8181
      - 8081
    volumes:
      - calibre_config:/config
    shm_size: 1gb
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    volumes:
      - calibre_data:/config
      - calibre_library:/books
    # ports:
    #   - 8083
    restart: unless-stopped

  wordpress-db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    # ports:
    #   - 80
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress


volumes:
  db_data:
  calibre_config:
  calibre_data:
  calibre_library: