services:
  local-ai:
    image: localai/localai:master-gpu-nvidia-cuda-13
    container_name: local-ai
    stdin_open: true
    tty: true
    restart: unless-stopped
    ports:
      - 8080
    environment:
      - LOCALAI_AUTH=true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # volumes:
    #   - ./models:/build/models:cached
    #   - ./images:/build/images:cached
    #   - ./config:/build/config:cached
